# Generated by Django 5.0.4 on 2024-05-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Winkel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=6, null=True)),
                ('adress', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Apointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(max_length=50, verbose_name='Plaats')),
                ('postcode', models.CharField(max_length=6)),
                ('ordernr', models.CharField(max_length=100, verbose_name='OrderNR')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Prijs')),
                ('intern', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(null=True, verbose_name='datum Tijd')),
                ('client', models.CharField(max_length=100, verbose_name='Naam')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefoon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
                ('winkel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.winkel', verbose_name='Winkel')),
            ],
        ),
    ]
