# Generated by Django 5.0.4 on 2024-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apointments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='apointments',
            name='time',
        ),
        migrations.AddField(
            model_name='apointments',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
