# Generated by Django 5.0.4 on 2024-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winkel',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='winkel',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='apointments',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Datum Tijd'),
        ),
    ]
