# Generated by Django 5.0.4 on 2024-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_apointments_date_remove_apointments_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winkel',
            name='postcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
