# Generated by Django 5.0.4 on 2024-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_winkel_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='apointments',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
