# Generated by Django 5.0.4 on 2024-06-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepautoservice', '0002_rename_start_time_service_apointments_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_apointments',
            name='tijd',
            field=models.CharField(max_length=47, null=True, verbose_name='Tijd'),
        ),
    ]
