# Generated by Django 5.0.4 on 2024-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepautoservice', '0003_alter_service_apointments_tijd'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_apointments',
            name='naam',
            field=models.CharField(max_length=100, null=True, verbose_name='Naam'),
        ),
    ]
